sudo: false
cache: bundler
language: ruby
rvm:
- 2.3.1
addons:
  apt:
    packages:
    - libgecode-dev
env:
  global:
  - USE_SYSTEM_GECODE=true
  - secure: rz8Ej7Zx5zArH+OwuAsRB8CH0rZVKIAm6nhB29wg73d7FrMv6cWEl5/B2uQqlefqZ1GYosAifhmoW7lVB1S2O9pDPB8wSpr2P9dsaHEupad4jBi6rIufxoCrx3YZIFPcmvL71u2+STi021VQpsXjcwfP6h2i+pVkPXxVr0Ihv3U=
before_install: "gem install bundler"
bundler_args: "--binstubs=$PWD/bin --jobs 3 --retry 3"
script:
- "./bin/rake travis"
gemfile:
- test/gemfiles/chef-12.gemfile
- test/gemfiles/chef-12.1.gemfile
- test/gemfiles/chef-12.2.gemfile
- test/gemfiles/chef-12.3.gemfile
- test/gemfiles/chef-12.4.gemfile
- test/gemfiles/chef-12.5.gemfile
- test/gemfiles/chef-12.6.gemfile
- test/gemfiles/master.gemfile
